#!/usr/bin/env bash
# ============================================================
#  Start Kummo locally (Linux/macOS).
#  Usage: ./start-kummo.sh [env]
#    env = local (default) | prod | any .env.<name> file
#  Starts a small web server and opens the browser.
#  Stop it with Ctrl+C.
#  (User-facing messages below are in German on purpose.)
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

ENV="${1:-local}"
ENV_FILE=".env.${ENV}"

if [ ! -f "$ENV_FILE" ]; then
  echo
  echo "Umgebungsdatei '${ENV_FILE}' nicht gefunden."
  echo "Verfuegbare Umgebungen:"
  for f in .env.*; do echo "  - ${f#.env.}"; done
  echo
  exit 1
fi

# Read .env file and generate js/env.js
SUPABASE_URL=$(grep -E '^SUPABASE_URL=' "$ENV_FILE" | cut -d= -f2-)
SUPABASE_ANON_KEY=$(grep -E '^SUPABASE_ANON_KEY=' "$ENV_FILE" | cut -d= -f2-)

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo
  echo "SUPABASE_URL oder SUPABASE_ANON_KEY fehlt in '${ENV_FILE}'."
  echo
  exit 1
fi

cat > js/env.js <<EOF
// Auto-generated by start-kummo.sh — do not edit.
window.KummoEnv = {
  supabaseUrl: '${SUPABASE_URL}',
  supabaseAnonKey: '${SUPABASE_ANON_KEY}'
};
EOF

echo "Umgebung: ${ENV}"

PORT=5500
URL="http://localhost:${PORT}/index.html"

# Look for an available program to start the server.
if command -v python3 >/dev/null 2>&1; then
  SERVER=(python3 -m http.server "$PORT")
elif command -v python >/dev/null 2>&1; then
  SERVER=(python -m http.server "$PORT")
elif command -v npx >/dev/null 2>&1; then
  SERVER=(npx --yes serve -l "$PORT" .)
else
  echo
  echo "Es wurde weder Python noch Node.js gefunden."
  echo "Bitte installieren Sie Python: https://www.python.org/downloads/"
  echo
  exit 1
fi

echo "Kummo wird gestartet ..."
"${SERVER[@]}" &
SERVER_PID=$!

# Stop the server cleanly on exit (Ctrl+C).
trap 'kill "$SERVER_PID" 2>/dev/null || true' EXIT

# Wait briefly, then open the browser.
sleep 2
if command -v xdg-open >/dev/null 2>&1; then
  xdg-open "$URL" >/dev/null 2>&1 || true
elif command -v open >/dev/null 2>&1; then
  open "$URL" >/dev/null 2>&1 || true
fi

echo
echo "Kummo laeuft auf ${URL}"
echo "Zum Beenden: Strg+C druecken."
echo
wait "$SERVER_PID"
