@echo off
REM ============================================================
REM  Start Kummo locally (Windows).
REM  Usage: start-kummo.bat [env]
REM    env = local (default) ^| prod ^| any .env.^<name^> file
REM  For "local": starts Supabase (Docker) if not already running,
REM  then starts a web server and opens the browser.
REM  Close this window to stop it.
REM  (User-facing messages below are in English.)
REM ============================================================
setlocal
cd /d "%~dp0"

set "ENV=%~1"
if "%ENV%"=="" set "ENV=local"
set "ENV_FILE=.env.%ENV%"

if not exist "%ENV_FILE%" (
  echo.
  echo Environment file '%ENV_FILE%' not found.
  echo Available environments:
  for %%f in (.env.*) do echo   - %%~nf
  echo.
  pause
  exit /b 1
)

REM Read .env file and generate js\env.js
set "SUPABASE_URL="
set "SUPABASE_ANON_KEY="
for /f "usebackq tokens=1,* delims==" %%a in ("%ENV_FILE%") do (
  if "%%a"=="SUPABASE_URL" set "SUPABASE_URL=%%b"
  if "%%a"=="SUPABASE_ANON_KEY" set "SUPABASE_ANON_KEY=%%b"
)

if not defined SUPABASE_URL (
  echo SUPABASE_URL is missing in '%ENV_FILE%'.
  pause
  exit /b 1
)
if not defined SUPABASE_ANON_KEY (
  echo SUPABASE_ANON_KEY is missing in '%ENV_FILE%'.
  pause
  exit /b 1
)

> js\env.js echo // Auto-generated by start-kummo.bat — do not edit.
>> js\env.js echo window.KummoEnv = {
>> js\env.js echo   supabaseUrl: '%SUPABASE_URL%',
>> js\env.js echo   supabaseAnonKey: '%SUPABASE_ANON_KEY%'
>> js\env.js echo };

echo Environment: %ENV%

REM --- Supabase (local only) ---
if "%ENV%"=="local" (
  REM Stop any existing (possibly unhealthy) Supabase containers first
  npx supabase stop >nul 2>&1
  echo Starting local Supabase instance ...
  npx supabase start
)

REM --- Web server ---
set "PORT=5500"
set "URL=http://localhost:%PORT%/index.html"
set "SERVER="

REM Look for an available program to start the server.
python --version >nul 2>&1 && set "SERVER=python -m http.server %PORT%"
if not defined SERVER py --version >nul 2>&1 && set "SERVER=py -m http.server %PORT%"
if not defined SERVER where npx >nul 2>&1 && set "SERVER=npx --yes serve -l %PORT% ."

if not defined SERVER (
  echo.
  echo Neither Python nor Node.js was found.
  echo Please install Python: https://www.python.org/downloads/
  echo (Check "Add Python to PATH" during installation.)
  echo.
  pause
  exit /b 1
)

echo Starting Kummo ...
start "" /b %SERVER%

REM Wait briefly so the server is ready, then open the browser.
timeout /t 2 /nobreak >nul
start "" "%URL%"

echo.
echo Kummo is running at %URL%
echo Close this window to stop.
echo To stop Supabase: npx supabase stop
echo.
pause >nul
